export enum EArticleControllerAction {
  GET_HOME_CONTENT = 'GET_HOME_CONTENT',
  GET_HOME_CONTENT_REQUEST = 'GET_HOME_CONTENT_REQUEST',
  GET_HOME_CONTENT_SUCCESS = 'GET_HOME_CONTENT_SUCCESS',
  GET_HOME_CONTENT_FAILED = 'GET_HOME_CONTENT_FAILED',

  GET_SERVICE = 'GET_SERVICE',
  GET_SERVICE_REQUEST = 'GET_SERVICE_REQUEST',
  GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS',
  GET_SERVICE_FAILED = 'GET_SERVICE_FAILED',

  GET_POLICY = 'GET_POLICY',
  GET_POLICY_REQUEST = 'GET_POLICY_REQUEST',
  GET_POLICY_SUCCESS = 'GET_POLICY_SUCCESS',
  GET_POLICY_FAILED = 'GET_POLICY_FAILED',

  GET_RULE = 'GET_RULE',
  GET_RULE_REQUEST = 'GET_RULE_REQUEST',
  GET_RULE_SUCCESS = 'GET_RULE_SUCCESS',
  GET_RULE_FAILED = 'GET_RULE_FAILED',

  GET_CONTACT = 'GET_CONTACT',
  GET_CONTACT_REQUEST = 'GET_CONTACT_REQUEST',
  GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS',
  GET_CONTACT_FAILED = 'GET_CONTACT_FAILED',

  GET_ABOUT_US = 'GET_ABOUT_US',
  GET_ABOUT_US_REQUEST = 'GET_ABOUT_US_REQUEST',
  GET_ABOUT_US_SUCCESS = 'GET_ABOUT_US_SUCCESS',
  GET_ABOUT_US_FAILED = 'GET_ABOUT_US_FAILED',
}
