export enum EArticleControllerAction {
  GET_HOME_CONTENT = 'GET_HOME_CONTENT',
  GET_HOME_CONTENT_REQUEST = 'GET_HOME_CONTENT_REQUEST',
  GET_HOME_CONTENT_SUCCESS = 'GET_HOME_CONTENT_SUCCESS',
  GET_HOME_CONTENT_FAILED = 'GET_HOME_CONTENT_FAILED',

  GET_SERVICE = 'GET_SERVICE',
  GET_SERVICE_REQUEST = 'GET_SERVICE_REQUEST',
  GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS',
  GET_SERVICE_FAILED = 'GET_SERVICE_FAILED',

  GET_POLICY = 'GET_POLICY',
  GET_POLICY_REQUEST = 'GET_POLICY_REQUEST',
  GET_POLICY_SUCCESS = 'GET_POLICY_SUCCESS',
  GET_POLICY_FAILED = 'GET_POLICY_FAILED',

  GET_RULE = 'GET_RULE',
  GET_RULE_REQUEST = 'GET_RULE_REQUEST',
  GET_RULE_SUCCESS = 'GET_RULE_SUCCESS',
  GET_RULE_FAILED = 'GET_RULE_FAILED',

  GET_CONTACT = 'GET_CONTACT',
  GET_CONTACT_REQUEST = 'GET_CONTACT_REQUEST',
  GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS',
  GET_CONTACT_FAILED = 'GET_CONTACT_FAILED',

  GET_ABOUT_US = 'GET_ABOUT_US',
  GET_ABOUT_US_REQUEST = 'GET_ABOUT_US_REQUEST',
  GET_ABOUT_US_SUCCESS = 'GET_ABOUT_US_SUCCESS',
  GET_ABOUT_US_FAILED = 'GET_ABOUT_US_FAILED',

  GET_ARTICLE_CATEGORY = 'GET_ARTICLE_CATEGORY',
  GET_ARTICLE_CATEGORY_REQUEST = 'GET_ARTICLE_CATEGORY_REQUEST',
  GET_ARTICLE_CATEGORY_SUCCESS = 'GET_ARTICLE_CATEGORY_SUCCESS',
  GET_ARTICLE_CATEGORY_FAILED = 'GET_ARTICLE_CATEGORY_FAILED',

  CREATE_UPDATE_ARTICLE = 'CREATE_UPDATE_ARTICLE',
  CREATE_UPDATE_ARTICLE_REQUEST = 'CREATE_UPDATE_ARTICLE_REQUEST',
  CREATE_UPDATE_ARTICLE_SUCCESS = 'CREATE_UPDATE_ARTICLE_SUCCESS',
  CREATE_UPDATE_ARTICLE_FAILED = 'CREATE_UPDATE_ARTICLE_FAILED',

  GET_ARTICLES = 'GET_ARTICLES',
  GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST',
  GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS',
  GET_ARTICLES_FAILED = 'GET_ARTICLES_FAILED',

  GET_ARTICLE = 'GET_ARTICLE',
  GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST',
  GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS',
  GET_ARTICLE_FAILED = 'GET_ARTICLE_FAILED',

  DELETE_ARTICLES = 'DELETE_ARTICLES',
  DELETE_ARTICLES_REQUEST = 'DELETE_ARTICLES_REQUEST',
  DELETE_ARTICLES_SUCCESS = 'DELETE_ARTICLES_SUCCESS',
  DELETE_ARTICLES_FAILED = 'DELETE_ARTICLES_FAILED',
}
