export enum EAccountControllerAction {
  GET_ACCOUNTS = 'GET_ACCOUNTS',
  GET_ACCOUNTS_REQUEST = 'GET_ACCOUNTS_REQUEST',
  GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS',
  GET_ACCOUNTS_FAILED = 'GET_ACCOUNTS_FAILED',

  GET_ACCOUNT = 'GET_ACCOUNT',
  GET_ACCOUNT_REQUEST = 'GET_ACCOUNT_REQUEST',
  GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS',
  GET_ACCOUNT_FAILED = 'GET_ACCOUNT_FAILED',

  GET_ALL_ROLES = 'GET_ALL_ROLES',
  GET_ALL_ROLES_REQUEST = 'GET_ALL_ROLES_REQUEST',
  GET_ALL_ROLES_SUCCESS = 'GET_ALL_ROLES_SUCCESS',
  GET_ALL_ROLES_FAILED = 'GET_ALL_ROLES_FAILED',

  CREATE_UPDATE_ACCOUNT = 'CREATE_UPDATE_ACCOUNT',
  CREATE_UPDATE_ACCOUNT_REQUEST = 'CREATE_UPDATE_ACCOUNT_REQUEST',
  CREATE_UPDATE_ACCOUNT_SUCCESS = 'CREATE_UPDATE_ACCOUNT_SUCCESS',
  CREATE_UPDATE_ACCOUNT_FAILED = 'CREATE_UPDATE_ACCOUNT_FAILED',

  DELETE_ACCOUNT = 'DELETE_ACCOUNT',
  DELETE_ACCOUNT_REQUEST = 'DELETE_ACCOUNT_REQUEST',
  DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS',
  DELETE_ACCOUNT_FAILED = 'DELETE_ACCOUNT_FAILED',

  CHANGE_PASSWORD_ACCOUNT = 'CHANGE_PASSWORD_ACCOUNT',
  CHANGE_PASSWORD_ACCOUNT_REQUEST = 'CHANGE_PASSWORD_ACCOUNT_REQUEST',
  CHANGE_PASSWORD_ACCOUNT_SUCCESS = 'CHANGE_PASSWORD_ACCOUNT_SUCCESS',
  CHANGE_PASSWORD_ACCOUNT_FAILED = 'CHANGE_PASSWORD_ACCOUNT_FAILED',
}
