export enum EBannerControllerAction {
  GET_BANNERS = 'GET_BANNERS',
  GET_BANNERS_REQUEST = 'GET_BANNERS_REQUEST',
  GET_BANNERS_SUCCESS = 'GET_BANNERS_SUCCESS',
  GET_BANNERS_FAILED = 'GET_BANNERS_FAILED',

  GET_BANNER = 'GET_BANNER',
  GET_BANNER_REQUEST = 'GET_BANNER_REQUEST',
  GET_BANNER_SUCCESS = 'GET_BANNER_SUCCESS',
  GET_BANNER_FAILED = 'GET_BANNER_FAILED',

  GET_LOGO = 'GET_LOGO',
  GET_LOGO_REQUEST = 'GET_LOGO_REQUEST',
  GET_LOGO_SUCCESS = 'GET_LOGO_SUCCESS',
  GET_LOGO_FAILED = 'GET_LOGO_FAILED',

  GET_HOME_BANNER = 'GET_HOME_BANNER',
  GET_HOME_BANNER_REQUEST = 'GET_HOME_BANNER_REQUEST',
  GET_HOME_BANNER_SUCCESS = 'GET_HOME_BANNER_SUCCESS',
  GET_HOME_BANNER_FAILED = 'GET_HOME_BANNER_FAILED',

  GET_BANNER_CATEGORY = 'GET_BANNER_CATEGORY',
  GET_BANNER_CATEGORY_REQUEST = 'GET_BANNER_CATEGORY_REQUEST',
  GET_BANNER_CATEGORY_SUCCESS = 'GET_BANNER_CATEGORY_SUCCESS',
  GET_BANNER_CATEGORY_FAILED = 'GET_BANNER_CATEGORY_FAILED',

  CREATE_UPDATE_BANNER = 'CREATE_UPDATE_BANNER',
  CREATE_UPDATE_BANNER_REQUEST = 'CREATE_UPDATE_BANNER_REQUEST',
  CREATE_UPDATE_BANNER_SUCCESS = 'CREATE_UPDATE_BANNER_SUCCESS',
  CREATE_UPDATE_BANNER_FAILED = 'CREATE_UPDATE_BANNER_FAILED',

  DELETE_BANNER = 'DELETE_BANNER',
  DELETE_BANNER_REQUEST = 'DELETE_BANNER_REQUEST',
  DELETE_BANNER_SUCCESS = 'DELETE_BANNER_SUCCESS',
  DELETE_BANNER_FAILED = 'DELETE_BANNER_FAILED',
}
