export enum EClientControllerAction {
  GET_CLIENTS = 'GET_CLIENTS',
  GET_CLIENTS_REQUEST = 'GET_CLIENTS_REQUEST',
  GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS',
  GET_CLIENTS_FAILED = 'GET_CLIENTS_FAILED',

  GET_CLIENT = 'GET_CLIENT',
  GET_CLIENT_REQUEST = 'GET_CLIENT_REQUEST',
  GET_CLIENT_SUCCESS = 'GET_CLIENT_SUCCESS',
  GET_CLIENT_FAILED = 'GET_CLIENT_FAILED',

  GET_CLIENT_EMPLOYEE = 'GET_CLIENT_EMPLOYEE',
  GET_CLIENT_EMPLOYEE_REQUEST = 'GET_CLIENT_EMPLOYEE_REQUEST',
  GET_CLIENT_EMPLOYEE_SUCCESS = 'GET_CLIENT_EMPLOYEE_SUCCESS',
  GET_CLIENT_EMPLOYEE_FAILED = 'GET_CLIENT_EMPLOYEE_FAILED',

  CREATE_UPDATE_CLIENT = 'CREATE_UPDATE_CLIENT',
  CREATE_UPDATE_CLIENT_REQUEST = 'CREATE_UPDATE_CLIENT_REQUEST',
  CREATE_UPDATE_CLIENT_SUCCESS = 'CREATE_UPDATE_CLIENT_SUCCESS',
  CREATE_UPDATE_CLIENT_FAILED = 'CREATE_UPDATE_CLIENT_FAILED',

  DELETE_CLIENT = 'DELETE_CLIENT',
  DELETE_CLIENT_REQUEST = 'DELETE_CLIENT_REQUEST',
  DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS',
  DELETE_CLIENT_FAILED = 'DELETE_CLIENT_FAILED',
}
