export enum EIconName {
  FacebookCircle = 'FacebookCircle',
  ZaloCircle = 'ZaloCircle',
  LinkedInCircle = 'LinkedInCircle',
  Menu = 'Menu',
  AngleRight = 'AngleRight',
  CloudDownload = 'CloudDownload',
  Video = 'Video',
  UserLine = 'UserLine',
  Calendar = 'Calendar',
  AngleDown = 'AngleDown',
  UserSquare = 'UserSquare',
  Locked = 'Locked',
  Book = 'Book',
  Logout = 'Logout',
  Phone = 'Phone',
  Facebook = 'Facebook',
  Wechat = 'Wechat',
}
export enum EIconColor {
  BLACK = '#000',
  WHITE = '#fff',
  SHAMROCK = '#35D298',
  SILVER = '#C4C4C4',
  MINE_SHAFT = '#222222',
  SHARK = '#2E3034',
  ROSE_WHITE = '#FFFAFA',
}
