export enum EDepotControllerAction {
  GET_DEPOT_STORAGES = 'GET_DEPOT_STORAGES',
  GET_DEPOT_STORAGES_REQUEST = 'GET_DEPOT_STORAGES_REQUEST',
  GET_DEPOT_STORAGES_SUCCESS = 'GET_DEPOT_STORAGES_SUCCESS',
  GET_DEPOT_STORAGES_FAILED = 'GET_DEPOT_STORAGES_FAILED',

  GET_DEPOT_ORDERS = 'GET_DEPOT_ORDERS',
  GET_DEPOT_ORDERS_REQUEST = 'GET_DEPOT_ORDERS_REQUEST',
  GET_DEPOT_ORDERS_SUCCESS = 'GET_DEPOT_ORDERS_SUCCESS',
  GET_DEPOT_ORDERS_FAILED = 'GET_DEPOT_ORDERS_FAILED',

  GET_DEPOT_STORAGES_SEARCH = 'GET_DEPOT_STORAGES_SEARCH',
  GET_DEPOT_STORAGES_SEARCH_REQUEST = 'GET_DEPOT_STORAGES_SEARCH_REQUEST',
  GET_DEPOT_STORAGES_SEARCH_SUCCESS = 'GET_DEPOT_STORAGES_SEARCH_SUCCESS',
  GET_DEPOT_STORAGES_SEARCH_FAILED = 'GET_DEPOT_STORAGES_SEARCH_FAILED',

  GET_DEPOT_ORDERS_RETURN_SEARCH = 'GET_DEPOT_ORDERS_RETURN_SEARCH',
  GET_DEPOT_ORDERS_RETURN_SEARCH_REQUEST = 'GET_DEPOT_ORDERS_RETURN_SEARCH_REQUEST',
  GET_DEPOT_ORDERS_RETURN_SEARCH_SUCCESS = 'GET_DEPOT_ORDERS_RETURN_SEARCH_SUCCESS',
  GET_DEPOT_ORDERS_RETURN_SEARCH_FAILED = 'GET_DEPOT_ORDERS_RETURN_SEARCH_FAILED',

  GET_DEPOT_ORDERS_RETURN = 'GET_DEPOT_ORDERS_RETURN',
  GET_DEPOT_ORDERS_RETURN_REQUEST = 'GET_DEPOT_ORDERS_RETURN_REQUEST',
  GET_DEPOT_ORDERS_RETURN_SUCCESS = 'GET_DEPOT_ORDERS_RETURN_SUCCESS',
  GET_DEPOT_ORDERS_RETURN_FAILED = 'GET_DEPOT_ORDERS_RETURN_FAILED',
}
